### ISSUE TITLE
[FEATURE] Add language support for Hindi (also build infrastructure for i18n)

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/CamperChan-discord#149]
**Is your feature request related to a problem? Please describe.**

Currently the bot only replies in English. But since fCC has open the Hindi Discord server, we may need to add support for Hindi replies from the bot.

**Describe the solution you'd like**

The bot should reply in English or Hindi according to the server. It will detect each server by using the server names or any other method.

We'll need to have a centralized place for the available replies of the bot, I suggest we have a `i18n.json` file where the bots replies are available in English and Hindi. A sample structure of the `i18n.json` file can be found [here](https://github.com/bradtaniguchi/discord-bot-test/pull/150).

**Additional context**

This issue, if resolved, should put the foundation required for the bot reply translations for other langs in the future if fCC needs it.

**Comment by naomi-lgbt** [comment]
While I'm all for the inclusiveness, is this something we need to implement ourselves? The bot serves as a POC/MVP but not the final product.

**Comment by bradtaniguchi** [comment]
I like the idea of adding support for the hindi server on the same bot, but this will require changing how the bot is currently setup for the current server for almost all user-facing messages along with complicating a lot of current features as the bot is currently design for **one** server only. If we use the **same** bot instance for both servers things might get complicated, or at least force a "mirroring" of the 2 servers, which becomes restrictive and annoying. This has less to do with translations, and more to do with just handling multiple servers at the same time.

As such having a separate discord bot instance might help decrease the bot's setup, but will increase hosting costs. In a perfect world a single bot instance will be able to handle both servers, but this will require a lot of work to do right. 

- The bot might be able to know what "locale" someone is in depending on the message/reaction property `guild` (which is the parent server) using something like [this](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=preferredLocale)

- The i18n.json translations should be written in the "right format". It doesn't seem like discordjs supports any i18n features, so we'd have to roll our own. However there seems to be a lot of docs on the subject, but none of them seem to apply to what we are currently doing.  **We should research about this more**, or at least start thinking about how the code should be written to interact with the i18n mappings

- When and how we send current messages isn't totally consistent. Sometime we send a message on an error and sometimes we don't, we should look into regulating/defining when this should happen since I think we only "kinda" follow a format.

**Comment by Twaha-Rahman** [comment]
I did some research on some big open source applications to see how they do **i18n** and found this ->

https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-core/lib/i18n

And they are keeping all the translations in a JSON file and switch messages on runtime. The JSON structure can be seen here ->

https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-core/lib/i18n/locales

**Comment by naomi-lgbt** [comment]
This one, I think, will wait until after migration.

**Comment by bradtaniguchi** [comment]
not going to do this, see #202
