### ISSUE TITLE
Add feature to format and prettify a code-block

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#17]
Given a message link/ref the bot should be able to do the following:
1. Determine what language it is (among supported list, determined)
  - probably a library out there **somewhere** that can help with this. Obviously if a message has text **and** code, the bot probably wont be able to differentiate. 
2. Format the code in backticks with the correct syntax highlighting using something like prettier to format the code sensibly
3. If at any point the bot can't format/understand the language, return a "sorry" like message.

This feature should only be called with the format similar to:
```
!format <message_link>
```

This shouldn't be ran all the time as this can be a CPU intensive task if ran all the time.

We also need to make sure we **don't** perform remote code execution, so we need libs well respected libs to handle the code formatting.

This command might also work just to format a given text block without a link to another message. 

**edit** we might be able to use the reactions feature to label code to "format":
https://discordjs.guide/popular-topics/reactions.html#awaiting-reactions

**Comment by Ryuno-Ki** [comment]
> probably a library out there somewhere that can help with this. Obviously if a message has text and code, the bot probably wont be able to differentiate.

GitHub itself is using [Linguist](https://github.com/github/linguist) for that.

**Comment by Ryuno-Ki** [comment]
> we might be able to use the reactions feature to label code to "format"

One idea was to use :robot: emoji to trigger them.

**Comment by bradtaniguchi** [comment]
> GitHub itself is using Linguist for that.

Linguist looks pretty heavy duty, and would require a ruby runtime which would increase the pre-req for this project beyond just node. Optimally we'd find a respectable node lib that we can leverage as-is, or piggieback on whatever the formatters use (if they work that way hehe)

**Comment by Twaha-Rahman** [comment]
Let's narrow down our target for now. We can start by creating an MVP release, which will format all web related languages. (For example -> `JavaScript,  TypeScript,  Flow, JSX, JSON,
CSS, SCSS, Less,
HTML, Vue, Angular,
GraphQL, Markdown, YAML`) All of these can be formatted using Prettier!

I am suggesting this because the majority of people in the FCC Discord are web devs and they share within these formats.

After we get the MVP release out, then we can focus on adding other languages too like-
1. Python
2. PHP
etc....
